language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

before_script:
  - composer self-update
  - composer install

script:
  - composer validate --strict
  - vendor/bin/phpstan analyse -c phpstan.neon -l max src/
  - vendor/bin/ecs check .
  - vendor/bin/phpunit